const mongoose = require('mongoose');

const { Schema } = mongoose;

const BotSchema = new Schema({
  _id: Schema.Types.ObjectId,
  name: String,
  abbreviation: String,
  outgoing: Map,
  enabled_platforms: [String],
  facebook: Map,
  line: Map,
  slack: Map,
  telegram: Map,
  whatsapp: Map,
  widget: Map,
  bot2bot: Map,
  gateway: Map,
  rabbitmq: new Schema({
    rabbitmq_uri: String,
    rabbitmq_gateway_to_chatbot: String,
    rabbitmq_chatbot_to_nlp: String,
    rabbitmq_nlp_to_chatbot: String,
    rabbitmq_chatbot_to_gateway: String,
    rabbitmq_gateway_to_livechat: String,
    rabbitmq_livechat_to_gateway: String,
    rabbitmq_bot2bot: String,
    rabbitmq_broadcast: String,
    rabbitmq_testing: String,
  }),
  redis: Map,
  chatbot: Map,
  nlp: Map,
  portal: Map,
  livechat: Map,
  monitor: Map,
  is_active: Boolean,
  // gender: String,
  // profile_pic_url: String,
  // auth_flag: Number,
  // is_broadcast_subscribed: Boolean,
  // last_active: Map,
  // bot_id: Schema.Types.ObjectId,
  // bot_user_group_id: Schema.Types.ObjectId,
  // platforms: [String],
  // facebook: Map,
  // chat_state: String,
  // created_at: Date,
  // created_by: String,
  // updated_at: Date,
  // updated_by: String,
  // is_active: Boolean,
}, { collection: 'bot', versionKey: false });

module.exports = mongoose.model('Bot', BotSchema);
