const mongoose = require('mongoose');

const { Schema } = mongoose;

const BotSchema = new Schema({
  name: String,
  abbreviation: String,
  outgoing: Map,
  enabled_platforms: [String],
  facebook: Map,
  line: Map,
  slack: Map,
  telegram: Map,
  whatsapp: Map,
  widget: Map,
  bot2bot: Map,
  gateway: Map,
  chatbot: {
    chatbot_uri: String,
    cloud_provider: String,
    cloud_access_key_id: String,
    cloud_secret_access_key: String,
    cloud_storage_url: String,
    cloud_bucket: String,
    msg_char_limit: Number,
    default_language: String,
    default_user_name: String,
    enable_multilanguage: Boolean,
    enabled_languages: [String],
    google_api_key: String,
    MAILGUN_KEY: String,
    rephrase_threshold: Schema.Types.Decimal128,
    refine_threshold: Schema.Types.Decimal128,
    feedback_threshold: Schema.Types.Decimal128,
    answer_threshold: Schema.Types.Decimal128,
    apschedules: [{}],
    non_text_entity: [String],
    reengagement_chatbots: [String],
  },
  rabbitmq: new Schema({
    rabbitmq_uri: String,
    rabbitmq_gateway_to_chatbot: String,
    rabbitmq_chatbot_to_nlp: String,
    rabbitmq_nlp_to_chatbot: String,
    rabbitmq_chatbot_to_gateway: String,
    rabbitmq_gateway_to_livechat: String,
    rabbitmq_livechat_to_gateway: String,
    rabbitmq_bot2bot: String,
    rabbitmq_broadcast: String,
    rabbitmq_testing: String,
  }),
  redis: Map,
  nlp: Map,
  portal: Map,
  livechat: {
    livechat_uri: String,
    livechat_enabled: Boolean,
    start_time: String,
    end_time: String,
    history_message_count: Number,
  },
  monitor: Map,
  is_active: Boolean,
}, { collection: 'bot', versionKey: false });

module.exports = mongoose.model('Bot', BotSchema);
